# Generated by Django 3.0.8 on 2020-10-03 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('photolink', models.CharField(default='student/default.jpg', max_length=100)),
                ('profilelink', models.CharField(max_length=100)),
                ('designation', models.BooleanField()),
                ('name', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField()),
                ('time', models.CharField(max_length=200, null=True)),
                ('link', models.URLField(null=True)),
                ('image', models.ImageField(null=True, upload_to='post/images')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
